// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentApi.Model;

namespace PaymentApi.model.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20210608152623_name_column")]
    partial class name_column
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PaymentApi.Model.PaymentDetails", b =>
                {
                    b.Property<int>("paymentDetalisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cardNumber")
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("cardOwnerName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("expirationDate")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("securityCode")
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("paymentDetalisId");

                    b.ToTable("PaymentDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
